dubbo:
  application:
    name: boot-user-service
  registry:
    protocol: zookeeper
    address: 127.0.0.1:2181
  protocol:
    name: dubbo
    port: 20880
  monitor: ## 连接到监控中心
    protocol: registry
  scan:
    base-packages: com.fleexy.dubbo.gmall

serviceimpl:
  num: 0