dubbo:
  application:
    name: boot-user-service
  registry:
    protocol: zookeeper
    address: 127.0.0.1:2181
  protocol:
    name: dubbo
    port: 20882
  monitor: ## 连接到监控中心
    protocol: registry